version: "3.9"
services:
  db:
    image: postgres
    #restart: always
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=my_blog
      - POSTGRES_USER=my_blog
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
